export const ROUTER_CONFIG = {
  MAX_MODELS_PER_CREDENTIAL: 5,
  MAX_CREDENTIALS_PER_REQUEST: 3,
  MAX_PROJECTS_PER_REQUEST: 3,
  MAX_TOTAL_ATTEMPTS: 5,
  PROVIDER_TIMEOUT_MS: 15000,
  FAILURE_THRESHOLD: 3, // For circuit breaking
  COOLDOWN_MINUTES: 5,  // Temporary cooldown duration
};
